# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

FROM python:3.9

WORKDIR /
COPY templates/deployment/local-quick-start/test_entrypoint.sh /test_entrypoint.sh
CMD ["bash", "/test_entrypoint.sh"]
