name: Documentation
on:
  workflow_dispatch:
    inputs:
      version:
        description: A documentation version to deploy (refs/tags/... or commit).
        required: true
        type: string

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Allow reading repository contents and publishing to Github Pages.
permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout specified version
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ inputs.version }}

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Install development tools
        run: pip install .[tests]

      - name: Generate documentation
        run: make documentation

      - name: Setup Github Pages
        uses: actions/configure-pages@c5a3e1159e0cbdf0845eb8811bd39e39fc3099c2 # v2.1.3

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@84bb4cd4b733d5c320c9c9cfbc354937524f4d64 # v1.0.10
        with:
          path: docs/_generated/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@f27bcc15848fdcdcc02f01754eb838e44bcf389b # v1.2.9